name: '🦫 Bucky'

on:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  bucky:
    # For PRs only, for comments only if user types @bucky
    if: |-
      (
        github.event_name == 'pull_request'
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.sender.type == 'User' &&
        startsWith(github.event.comment.body, '@bucky') &&
        contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
      )
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: 'actions/checkout@v5'

      - name: Run Bucky
        uses: Sonos-Inc/bucky@v1
